### ISSUE TITLE
Casting exception in TransposedPreferenceData

### ISSUE THREAD

**Issue by jacekwasilewski** [RankSys/RankSys#11]
Hi @saulvargas,

If you run `RecommenderExample` you will get:

```
Exception in thread "main" java.lang.ClassCastException: es.uam.eps.ir.ranksys.fast.preference.SimpleFastPreferenceData cannot be cast to es.uam.eps.ir.ranksys.fast.preference.FasterPreferenceData
    at es.uam.eps.ir.ranksys.fast.preference.TransposedPreferenceData.getUidxVs(TransposedPreferenceData.java:175)
    at es.uam.eps.ir.ranksys.nn.sim.VectorSimilarity.getFasterNorm2(VectorSimilarity.java:174)
    at es.uam.eps.ir.ranksys.nn.sim.VectorSimilarity.lambda$new$3(VectorSimilarity.java:62)
    at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:205)
    at java.util.stream.IntPipeline$9$1.accept(IntPipeline.java:344)
    at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
    at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateSequential(ForEachOps.java:189)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.IntPipeline.forEach(IntPipeline.java:404)
    at es.uam.eps.ir.ranksys.nn.sim.VectorSimilarity.<init>(VectorSimilarity.java:62)
    at es.uam.eps.ir.ranksys.nn.sim.VectorCosineSimilarity.<init>(VectorCosineSimilarity.java:37)
    at es.uam.eps.ir.ranksys.nn.item.sim.VectorCosineItemSimilarity.<init>(VectorCosineItemSimilarity.java:32)
    at es.uam.eps.ir.ranksys.examples.RecommenderExample.lambda$main$14(RecommenderExample.java:106)
    at es.uam.eps.ir.ranksys.examples.RecommenderExample.lambda$main$20(RecommenderExample.java:161)
    at java.util.HashMap.forEach(HashMap.java:1280)
    at es.uam.eps.ir.ranksys.examples.RecommenderExample.main(RecommenderExample.java:158)
```

Should your `TransposedPreferenceData` implement `FasterPreferenceData` if you are decorating `FastPreferenceData`?
In the `VectorSimilarity`, if you have an instance of `TransposedPreferenceData` that is decorating `SimpleFastPreferenceData` we fall into wrong if-case.

I do not know what was your intent - should we just have one `TransposedPreferenceData` that implements `FastPreferenceData` (I have checked that, if fixes the problem but I do not know if that does not affect other classes, I have seen casting of objects to `FasterPreferenceData` in other places and it makes harder to tell if that breaks something or not), or two implementations: `TransposedFastPreferenceData` and `TransposedFasterPreferenceData`?

Jacek.

**Comment by saulvargas** [comment]
Hi @jacekwasilewski 

Good catch! There is clearly a design flaw here (and a lack of proper pre-release testing on my side, but that's a different story). I might just merge the FastPreferenceData and FasterPreferenceData. That would solve the issue for now. What do you think?

Saúl

**Comment by jacekwasilewski** [comment]
Having one interface probably would be the simplest solution for now - also, from the use point of view one could think "if something is Faster, what is the point of using something that is only Fast".

**Comment by saulvargas** [comment]
Hi @jacekwasilewski 

Could you please help me check that the changes made in branch "fixissue11" that I just pushed (https://github.com/RankSys/RankSys/tree/fixissue11) fix this bug?

Now FastPreferenceData implements the methods of the former FasterPreferenceData and includes an extra method indicating which set of methods are preferred (but not mandatory) when accessing the data.

Saúl

**Comment by jacekwasilewski** [comment]
Hi @saulvargas,

I have run the same experiment using your fix and everything is OK.

We could think later what to do to prevent using `UnsupportedOperationExceptions` in `PLSAFactorizer.java` but this should be ok for now.

Jacek.

**Comment by saulvargas** [comment]
The UnsupportedOperationExceptions should not be a problem, PLSAPreferenceData is private and under control. Thanks!
