### ISSUE TITLE
Problem in reading the ml-100k dataset for trainData in the example 

### ISSUE THREAD

**Issue by anis016** [RankSys/RankSys#52]
Hello,

I was planning to use RankSys for one the project that I am doing in Java.
I tried to run the example RecommenderExample code given for the movie recommendation but while reading the data I am always stuck up in ArrayIndexOutOfBoundsException issue.

This is how I am reading the data.

`String userPath = "/home/anis/Java_Workspace/u.user";
 String itemPath = "/home/anis/Java_Workspace/u.item";
 String trainDataPath = "/home/anis/Java_Workspace/u1.base";
 String testDataPath = "/home/anis/Java_Workspace/u1.test";
 FastUserIndex<Long> userIndex = SimpleFastUserIndex.load(UsersReader.read(userPath, lp));
 FastItemIndex<Long> itemIndex = SimpleFastItemIndex.load(ItemsReader.read(itemPath, lp));
 FastPreferenceData<Long, Long> trainData = SimpleFastPreferenceData.load(SimpleRatingPreferencesReader.get().read(trainDataPath, lp, lp), userIndex, itemIndex);
        FastPreferenceData<Long, Long> testData = SimpleFastPreferenceData.load(SimpleRatingPreferencesReader.get().read(testDataPath, lp, lp), userIndex, itemIndex);`

`FastPreferenceData<Long, Long> trainData = SimpleFastPreferenceData.load(SimpleRatingPreferencesReader.get().read(trainDataPath, lp, lp), userIndex, itemIndex);` --> This line is throwing the error.

Error::
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at es.uam.eps.ir.ranksys.fast.preference.SimpleFastPreferenceData.lambda$load$14(SimpleFastPreferenceData.java:243)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at es.uam.eps.ir.ranksys.fast.preference.SimpleFastPreferenceData.load(SimpleFastPreferenceData.java:237)
	at es.uam.eps.ir.ranksys.fast.preference.SimpleFastPreferenceData.load(SimpleFastPreferenceData.java:196)
	at com.deeplearning.rs.FactorizationMachine.main(FactorizationMachine.java:49)`

The data set is ml-100k dataset.

I am bit confused about this. Is there anything else I need to do to the dataset or is there any other way I can read the dataset ??

Thanks

**Comment by JavierSanzCruza** [comment]
Hello,

I think your problem might be caused by the u.user and u.item files you are using. The version of this files provided with the movielens-100k dataset includes not only the identifiers of the users / items, but plenty of additional information. UserReader/ItemReader classes only need the first field of those files (the identifier of the corresponding user/item). If the identifiers were separated by tabs from the rest of the information, it could work. However, in u.user and u.item, they are separated by '|' characters.

I would suggest you to create two new files: a file userIndex.txt which contains just the identifiers of the users (one in each line), and a itemIndex.txt file which contains the identifiers of the items (one in each line). These files should, respectively, be the paths referenced in variables `userPath` and `itemPath`

I hope this helps you

**Comment by anis016** [comment]
Thank you !

That was exactly the problem.. and now it worked ! Was able to run the Recommender and get the output file as well.

Could you please able to help me about one more thing ...
So, the fm-rmse is generated in this way

402	127	0.9835266055943525
402	405	0.9410559667572137
402	284	0.9343284158253462
402	151	0.9180604049936395
402	121	0.905954764907684
402	174	0.890890200226765
402	129	0.8764127685700212
402	14	0.8701571693405967
402	111	0.8588124106130095
402	283	0.8531912817603047
402	7	0.848111055951372
.
.
.
.

What I understand is, it is the recommended movies(2nd column) for that user(1st column) and how they would actually give the rating(3rd column) ? am I right ?

**Comment by JavierSanzCruza** [comment]
As you said, the first column represents the user, the second represents the movie the system recommends to the user. The third is the score the recommendation algorithm generates for that user and movie pair. It should be noted that the recommendation rating is not necessarily a prediction of a possible future rating.

**Comment by anis016** [comment]
Fantastic ! thank you so much ... I am closing this issue :+1:
